services:
  redis:
    image: redis:8.4.0-alpine
    ports:
      - "6379:6379"

  api-service:
    build:
      context: .
      dockerfile: apps/api-service/Dockerfile
    # ports:
    #   - "3001:3001"
    environment:
      - REDIS_URL=redis://localhost:6379
    env_file:
      - ./apps/api-service/.env
    depends_on:
      - redis

  engine-service:
    build:
      context: .
      dockerfile: apps/engine-service/Dockerfile
    # ports:
    #   - "3002:3002"
    environment:
      - REDIS_URL=redis://localhost:6379
    env_file:
      - ./apps/engine-service/.env
    depends_on:
      - redis

  price-poller-service:
    build:
      context: .
      dockerfile: apps/price-poller-service/Dockerfile
    # ports:
    #   - "3003:3003"
    environment:
      - REDIS_URL=redis://localhost:6379
    env_file:
      - ./apps/price-poller-service/.env
    depends_on:
      - redis
