FROM node:22.18-alpine AS base

RUN apk add --no-cache wget
RUN npm install -g bun turbo

WORKDIR /app
COPY . .

RUN turbo prune --scope=web --docker

FROM node:22.18-alpine AS builder

RUN apk add --no-cache wget
RUN npm install -g bun

WORKDIR /app

COPY --from=base /app/out/json/ ./
COPY --from=base /app/out/bun.lock ./bun.lock
COPY --from=base /app/turbo.json ./turbo.json

RUN bun install

COPY --from=base /app/out/full/ .

# FORCE BUILD (disable turbo cache)
WORKDIR /app
RUN bunx turbo run build --filter=web --no-cache

FROM node:22.18-alpine AS runner

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN apk add --no-cache wget
RUN npm install -g bun

WORKDIR /app

# Copy FULL workspace output
COPY --from=builder --chown=node:node /app /app

USER node

WORKDIR /app/apps/web

EXPOSE 3000

CMD ["bun", "run", "start"]
