FROM oven/bun:1.2 AS base

RUN bun add -g turbo

WORKDIR /app
COPY . .

RUN turbo prune --scope=web --docker

FROM oven/bun:1.2 AS builder

WORKDIR /app

COPY --from=base /app/out/json/ ./
COPY --from=base /app/out/bun.lock ./bun.lock
COPY --from=base /app/turbo.json ./turbo.json

RUN bun install

COPY --from=base /app/out/full/ .

# Next.js build
WORKDIR /app
RUN bunx turbo run build --filter=web --no-cache

FROM oven/bun:1.2 AS runner

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /app

# Copy FULL workspace output
COPY --from=builder /app /app

WORKDIR /app/apps/web

EXPOSE 3000

CMD ["bun", "run", "start"]
