name: Docker Build and Push

on:
  push:
    tags:
      - 'v*.*.*'   # run only semantic version tags like v1.2.3
  workflow_dispatch:

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Build & Push ${{ matrix.service }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - service: api-service
            dockerfile: Dockerfile.api-service
            service_tag: api
          - service: engine-service
            dockerfile: Dockerfile.engine
            service_tag: engine
          - service: price-poller-service
            dockerfile: Dockerfile.price-poller
            service_tag: price-poller
          - service: web
            dockerfile: Dockerfile.web
            service_tag: web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version info
        id: vars
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "major=$(echo $VERSION | cut -d. -f1)" >> $GITHUB_OUTPUT
          echo "minor=$(echo $VERSION | cut -d. -f2)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true

          platforms: linux/amd64,linux/arm64 # this will create image for both cpu architecture

          tags: |
            imgbox/${{ matrix.service_tag }}:latest
            imgbox/${{ matrix.service_tag }}:v${{ steps.vars.outputs.version }}
            imgbox/${{ matrix.service_tag }}:v${{ steps.vars.outputs.major }}
            imgbox/${{ matrix.service_tag }}:v${{ steps.vars.outputs.major }}.${{ steps.vars.outputs.minor }}

          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ github.ref_name }}

          build-args: |
            APP_VERSION=${{ github.ref_name }}

          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Security scan
      - name: Scan image
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: imgbox/${{ matrix.service_tag }}:v${{ steps.vars.outputs.version }}